# Generated by Django 5.2.1 on 2025-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_category_color_category_icon_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional emoji or icon', max_length=30),
        ),
    ]
